# -*- coding: utf-8 -*-
"""Assignment-12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1__xfa6N1ufn_SvAYRVkAopliM2nsRe1U
"""

1. In what modes should the PdfFileReader() and PdfFileWriter() File objects will be opened?

!pip install PyPDF2
Collecting PyPDF2
  Downloading PyPDF2-1.26.0.tar.gz (77 kB)
     |████████████████████████████████| 77 kB 3.1 MB/s 
Building wheels for collected packages: PyPDF2
  Building wheel for PyPDF2 (setup.py) ... done
  Created wheel for PyPDF2: filename=PyPDF2-1.26.0-py3-none-any.whl size=61100 sha256=f86d38131b05c1d595e66639eef80198eec8a0ae2396db736db124eaaf26c2a7
  Stored in directory: /root/.cache/pip/wheels/80/1a/24/648467ade3a77ed20f35cfd2badd32134e96dd25ca811e64b3
Successfully built PyPDF2
Installing collected packages: PyPDF2
Successfully installed PyPDF2-1.26.0

2. From a PdfFileReader object, how do you get a Page object for page 5?

Ans. Calling getPage(4) will return a Page object for page 5 since page 0 is the first page

import PyPDF2 as pdf
pdfFileObj = open("cardealer.pdf",'rb')
pdfReader = pdf.PdfFileReader(pdfFileObj)
pageObj = pdfReader.getPage(4)
pageObj.extractText()

3. What PdfFileReader variable stores the number of pages in the PDF document?

import PyPDF2 as pdf
pdfFileObj = open("cardealer.pdf",'rb')
pdfReader = pdf.PdfFileReader(pdfFileObj)
pdfReader.numPages

4. If a PdfFileReader object’s PDF is encrypted with the password swordfish, what must you do before you can obtain Page objects from it?

Ans. Before we obtain the page object, the pdf has to be decrypted by calling .decrypt('swordfish')

5. What methods do you use to rotate a page?

#pageObj.rotateClockwise(180)

#The rotateClockwise() and rotateCounterClockwise() methods. The degrees to rotate is passed as an integer argument

6. What is the difference between a Run object and a Paragraph object?

i.Paragraph Object : A document contains multiple paragraphs. A paragraph begins on a new line and contains multiple
runs. The Document object contains a list of Paragraph objects for the paragraphs in the document. (A new paragraph begins whenever the user presses ENTER or RETURN while typing in a Word document.)

ii.Run Objects : Runs are contiguous groups of characters within a paragraph with the same style

7. How do you obtain a list of Paragraph objects for a Document object that’s stored in a variable named doc?

#!pip install python-docx
import docx
doc = docx.Document('abc.docx')
doc.paragraphs
#By using doc.paragraphs

8. What type of object has bold, underline, italic, strike, and outline variables?

Ans. A Run object has bold, underline,italic,strike and outline variables

9. What is the difference between False, True, and None for the bold variable?

i.Runs can be further styled using text attributes. Each attribute can be set to one of three values:
True (the attribute is always enabled, no matter what other styles are applied to the run),
False (the attribute is always disabled),
None (defaults to whatever the run’s style is set to)

ii.True always makes the Run object bolded and False makes it always not bolded, no matter what the style’s bold setting is. None will make the Run object just use the style’s bold setting

10. How do you create a Document object for a new Word document?

Ans. By Calling the docx.Document() function.

11. How do you add a paragraph with the text 'Hello, there!' to a Document object stored in a variable named doc?

import docx
doc = docx.Document()

doc.add_paragraph('Hello there!')
doc.save('hellothere.docx')

12. What integers represent the levels of headings available in Word documents?

i.integer from 0 to 4
ii.The arguments to add_heading() are a string of the heading text and an integer from 0 to 4. The integer 0 makes the heading the Title style, which is used for the 
top of the document. Integers 1 to 4 are for various heading levels, with 1 being the main heading and 4 the lowest subheading